FlixNTix/Controllers/ActorController.cs
using FlixNTix.Data;
using FlixNTix.Data.Interfaces;
using FlixNTix.Data.Static;
using FlixNTix.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlixNTix.Controllers;

[Authorize(Roles = UserRoles.Admin)]
public class ActorController : Controller
{

    private readonly IActorService _service;

    public ActorController(IActorService service)
    {
        _service = service;
    }

    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        var allActors = await _service.GetAllAsync();
        return View(allActors);
    }

    //Get request: actors/create
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor)
    {
        if (!ModelState.IsValid)
        {
            return View(actor);
        }
        await _service.AddAsync(actor);
        return RedirectToAction(nameof(Index));
    }

    //get: actor/details
    [AllowAnonymous]

    public async Task<IActionResult> Details(int id)
    {
        var actorDetails = await _service.GetByIdAsync(id);
        if (actorDetails == null) return View("NotFound");
        return View(actorDetails);

    }

    //Get request: actors/edit
    public async Task<IActionResult> Edit(int id)
    {
        var actorDetails = await _service.GetByIdAsync(id);
        if (actorDetails == null) return View("NotFound");
        return View(actorDetails);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Actor actor)
    {
        if (!ModelState.IsValid)
        {
            return View(actor);
        }
        await _service.UpdateAsync(id, actor);
        return RedirectToAction(nameof(Index));
    }

    //Get request: actors/delete
    public async Task<IActionResult> Delete(int id)
    {
        var actorDetails = await _service.GetByIdAsync(id);
        if (actorDetails == null) return View("NotFound");
        return View(actorDetails);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var actorDetails = await _service.GetByIdAsync(id);
        if (actorDetails == null) return View("NotFound");

        await _service.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
}

FlixNTix/Controllers/MovieController.cs
using FlixNTix.Data;
using FlixNTix.Data.Interfaces;
using FlixNTix.Data.Static;
using FlixNTix.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace FlixNTix.Controllers;

[Authorize(Roles = UserRoles.Admin)]
public class MovieController : Controller
{
    private readonly IMovieService _service;
    public MovieController(IMovieService service)
    {
        _service = service;
    }

    //index
    [AllowAnonymous]

    public async Task<IActionResult> Index()
    {
        var allMovies = await _service.GetAllAsync(n => n.Theater);
        return View(allMovies);
    }

    //search filer
    [AllowAnonymous]

    public async Task<IActionResult> Filter(string searchString)
    {
        var allMovies = await _service.GetAllAsync(n => n.Theater);

        if (!string.IsNullOrEmpty(searchString))
        {
            var filteredResult = allMovies.Where(n => n.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase) || 
            n.Description.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();
            return View("Index", filteredResult);
        }
        return View("NotFound");
    }

    //get - movies/details
    [AllowAnonymous]


    public async Task<IActionResult> Details(int id)
    {
        var movieDetails = await _service.GetMovieByIdAsync(id);
        return View(movieDetails);
    }

    //get - movies/create

    public async Task<IActionResult> Create()
    {
        var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

        ViewBag.Theaters = new SelectList(movieDropdownsData.Theaters, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
        
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> Create(NewMovieVM movie)
    {
        if (!ModelState.IsValid)
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Theaters = new SelectList(movieDropdownsData.Theaters, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(movie);
        }
        await _service.AddNewMovieAsync(movie);
        return RedirectToAction(nameof(Index));
    }

    //get - movies/edit

    public async Task<IActionResult> Edit(int id)
    {
        var movieDetails = await _service.GetMovieByIdAsync(id);
        if (movieDetails == null) return View("NotFound");

        var response = new NewMovieVM()
        {
            Id = movieDetails.Id,
            Name = movieDetails.Name,
            Description = movieDetails.Description,
            Price = movieDetails.Price,
            StartDate = movieDetails.StartDate,
            EndDate = movieDetails.EndDate,
            ImageURL = movieDetails.ImageURL,
            MovieCategory = movieDetails.MovieCategory,
            TheaterId = movieDetails.TheaterId,
            ProducerId = movieDetails.ProducerId,
            ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),
        };

        var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

        ViewBag.Theaters = new SelectList(movieDropdownsData.Theaters, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

        return View(response);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, NewMovieVM movie)
    {
        if (id != movie.Id) return View("NotFound");

        if (!ModelState.IsValid)
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Theaters = new SelectList(movieDropdownsData.Theaters, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(movie);
        }
        await _service.UpdateMovieAsync(movie);
        return RedirectToAction(nameof(Index));
    }

    //privacy and error views
    [AllowAnonymous]

    public IActionResult Privacy()
    {
        ViewData["Welcome"] = "Welcome To The Vault";
        ViewBag.Description = "This Is How We Do";
        return View();
    }

    [AllowAnonymous]

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FlixNTix/Controllers/OrderController.cs
using FlixNTix.Data.Cart;
using FlixNTix.Data.Interfaces;
using FlixNTix.Data.Repositories;
using FlixNTix.Data.Static;
using FlixNTix.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FlixNTix.Controllers;

[Authorize]
public class OrderController : Controller
{
    private readonly IMovieService _movieService;
    private readonly ShoppingCart _shoppingCart;
    private readonly IOrderService _orderService;
    public OrderController(IMovieService movieService, ShoppingCart shoppingCart, IOrderService orderService)
    {
        _movieService = movieService;
        _shoppingCart = shoppingCart;
        _orderService = orderService;
    }

    public async Task<IActionResult> Index()
    {
        string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        string userRole =User.FindFirstValue(ClaimTypes.Role);
        var orders = await _orderService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
        return View(orders);
    }
    public IActionResult ShoppingCart()
    {
        var items = _shoppingCart.GetShoppingCartItems();

        _shoppingCart.ShoppingCartItems = items;
        var response = new ShoppingCartVM()
        {
            ShoppingCart = _shoppingCart,
            ShoppingCartTotal = _shoppingCart.GetshoppingCartTotal()
        };

        return View(response);
    }

    public async Task<IActionResult> AddItemToShoppingCart(int id)
    {
        var item = await _movieService.GetMovieByIdAsync(id);
        if (item != null)
        {
            _shoppingCart.AddItemToCart(item);
        }
        return RedirectToAction(nameof(ShoppingCart));
    }

    public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
    {
        var item = await _movieService.GetMovieByIdAsync(id);

        if (item != null)
        {
            _shoppingCart.RemoveItemFromCart(item);
        }
        return RedirectToAction(nameof(ShoppingCart));
    }

    public async Task<IActionResult> CompleteOrder()
    {
        var items = _shoppingCart.GetShoppingCartItems();
        string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

        await _orderService.StoreOrderAsync(items, userId, userEmailAddress);
        await _shoppingCart.ClearShoppingCartAsync();

        return View("OrderCompleted");
    }
}

FlixNTix/Controllers/TheaterController.cs
using FlixNTix.Data;
using FlixNTix.Data.Interfaces;
using FlixNTix.Data.Static;
using FlixNTix.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlixNTix.Controllers;
[Authorize(Roles = UserRoles.Admin)]
public class TheaterController : Controller
{
    private readonly ITheaterService _service;

    public TheaterController(ITheaterService service)
    {
        _service = service;
    }

    //index 
    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        var allTheaters = await _service.GetAllAsync();
        return View(allTheaters);
    }

    //get - theater/create
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Theater theater)
    {
        if (!ModelState.IsValid) return View(theater);

        await _service.AddAsync(theater);
        return RedirectToAction(nameof(Index));
    }

    //get - theater/details
    [AllowAnonymous]

    public async Task<IActionResult> Details(int id)
    {
        var theaterDetails = await _service.GetByIdAsync(id);
        if (theaterDetails == null) return View("NotFound");
        return View(theaterDetails);
    }

    //get - theater/edit

    public async Task<IActionResult> Edit(int id)
    {
        var theaterDetails = await _service.GetByIdAsync(id);
        if (theaterDetails == null) return View("NotFound");
        return View(theaterDetails);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Theater theater)
    {
        if (!ModelState.IsValid) return View(theater);

        if (id == theater.Id)
        {
            _service.UpdateAsync(id, theater);
            return RedirectToAction(nameof(Index));
        }
        return View(theater);
    }

    //get - producer/delete

    public async Task<IActionResult> Delete(int id)
    {
        var theaterDetails = await _service.GetByIdAsync(id);
        if (theaterDetails == null) return View("NotFound");
        return View(theaterDetails);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {

        var theaterDetails = await _service.GetByIdAsync(id);
        if (theaterDetails == null) return View("NotFound");

        await _service.DeleteAsync(id);
        return RedirectToAction(nameof(Index));

    }
}

FlixNTix/Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-6 offset-3">
    <h1 class="text-warning">You have reached the end of the internet. Either you are trying to acces that which you cannot, 
        or your search yielded no results. Reflect upon your journey and the choices you've made. What have you learned? Let us go
        back to the beginning and try again, shall we?</h1>
    <hr />
    <a class="btn btn-lg btn-outline-secondary text-white" asp-controller="Movie" asp-action="Index">Restart Journey</a>
    </div>
</div>

FlixNTix/Views/Shared/_CreateItem.cshtml
@model string;



@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-outline-success text-white float-end" style="margin-bottom:100px">
            <i class="bi bi-plus-circle" style="padding-right: 2px"></i> Add New
        </a>
    </div>
}

FlixNTix/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;



@*Identity Buttons*@
@*note to self - views preceded with an underscore are typically a way of identifying a "partial view"*@
@if(!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success m-2" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i>  Log In
    </a>
    <a class="btn btn-outline-info m-2" asp-controller="Account" asp-action="Register">
    <i class="bi bi-person-plus"></i>  Register
</a>

}else 
{
    @*User Profile Section*@
    <div class="dropdown px-3">
        <button class="btn btn-outline-info dropdown-toggle" type="button" id="profile-btn" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Order" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger m-2">
            <i class="bi bi-box-arrow-left"></i>  Logout
        </button>
    </form>
}

FlixNTix/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlixNTix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlixNTix.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand fs-1 text-decoration-underline" asp-area="" asp-controller="Movie" asp-action="Index">FlixN'Tix</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light fs-5" asp-area="" asp-controller="Movie" asp-action="Index"><i class="bi bi-film"></i> Movies</a>
                        </li>

                        @if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle fs-5" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu bg-secondary border-white" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item fw-bold" asp-controller="Theater" asp-action="Index"><i class="bi bi-camera-reels"></i> Theaters</a>
                                    <a class="dropdown-item fw-bold" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                    <a class="dropdown-item fw-bold" asp-controller="Actor" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                </div>
                            </li>
                        }
                        
                    </ul>

                    <form class="input-group-text m-2" asp-controller="Movie" asp-action="Filter">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie...">
                        <button class="btn btn-secondary btn-outline-white float-sm-end" type="submit"><i class="bi bi-search "></i></button> 
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>
                    @*@await Html.RenderPartialAsync("_Identity")*@                     
                    <partial name="_Identity.cshtml" />  @*this is another way of doing the above line*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="position:fixed; left: 0; bottom: 0; width: 100%; footer text-white ">
        <div class="container-fluid">
            &copy; 2022 - FlixNTix - <a asp-area="" asp-controller="Movie" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>