FlixNTix/Models/Movie.cs
using FlixNTix.Data.Base;
using FlixNTix.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FlixNTix.Models;

public class Movie : IEntityBase
{
    [Key]
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public double Price { get; set; }
    public string ImageURL { get; set; }
    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }
    public MovieCategory MovieCategory { get; set; }

    //movie to actor relationship
    public List<Actor_Movie> Actors_Movies { get; set; }

    //movie to theater relationship
    public int TheaterId { get; set; }
    [ForeignKey("TheaterId")]

    public Theater Theater { get; set; }

    //move to producer relationship
    public int ProducerId { get; set; }
    [ForeignKey("ProducerId")]

    public Producer Producer { get; set; }
}

FlixNTix/Controllers/ActorController.cs
using FlixNTix.Data;
using FlixNTix.Data.Interfaces;
using FlixNTix.Data.Static;
using FlixNTix.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlixNTix.Controllers;

[Authorize(Roles = UserRoles.Admin)]
public class ActorController : Controller
{

    private readonly IActorService _service;

    public ActorController(IActorService service)
    {
        _service = service;
    }

    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        var allActors = await _service.GetAllAsync();
        return View(allActors);
    }

    //Get request: actors/create
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor)
    {
        if (!ModelState.IsValid)
        {
            return View(actor);
        }
        await _service.AddAsync(actor);
        return RedirectToAction(nameof(Index));
    }

    //get: actor/details
    [AllowAnonymous]

    public async Task<IActionResult> Details(int id)
    {
        var actorDetails = await _service.GetByIdAsync(id);
        if (actorDetails == null) return View("NotFound");
        return View(actorDetails);

    }

    //Get request: actors/edit
    public async Task<IActionResult> Edit(int id)
    {
        var actorDetails = await _service.GetByIdAsync(id);
        if (actorDetails == null) return View("NotFound");
        return View(actorDetails);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Actor actor)
    {
        if (!ModelState.IsValid)
        {
            return View(actor);
        }
        await _service.UpdateAsync(id, actor);
        return RedirectToAction(nameof(Index));
    }

    //Get request: actors/delete
    public async Task<IActionResult> Delete(int id)
    {
        var actorDetails = await _service.GetByIdAsync(id);
        if (actorDetails == null) return View("NotFound");
        return View(actorDetails);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var actorDetails = await _service.GetByIdAsync(id);
        if (actorDetails == null) return View("NotFound");

        await _service.DeleteAsync(id);
        return RedirectToAction(nameof(Index));
    }
}

FlixNTix/Controllers/MovieController.cs
using FlixNTix.Data;
using FlixNTix.Data.Interfaces;
using FlixNTix.Data.Static;
using FlixNTix.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace FlixNTix.Controllers;

[Authorize(Roles = UserRoles.Admin)]
public class MovieController : Controller
{
    private readonly IMovieService _service;
    public MovieController(IMovieService service)
    {
        _service = service;
    }

    //index
    [AllowAnonymous]

    public async Task<IActionResult> Index()
    {
        var allMovies = await _service.GetAllAsync(n => n.Theater);
        return View(allMovies);
    }

    //search filer
    [AllowAnonymous]

    public async Task<IActionResult> Filter(string searchString)
    {
        var allMovies = await _service.GetAllAsync(n => n.Theater);

        if (!string.IsNullOrEmpty(searchString))
        {
            var filteredResult = allMovies.Where(n => n.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase) || 
            n.Description.Contains(searchString, StringComparison.OrdinalIgnoreCase)).ToList();
            return View("Index", filteredResult);
        }
        return View("NotFound");
    }

    //get - movies/details
    [AllowAnonymous]


    public async Task<IActionResult> Details(int id)
    {
        var movieDetails = await _service.GetMovieByIdAsync(id);
        return View(movieDetails);
    }

    //get - movies/create

    public async Task<IActionResult> Create()
    {
        var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

        ViewBag.Theaters = new SelectList(movieDropdownsData.Theaters, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");
        
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> Create(NewMovieVM movie)
    {
        if (!ModelState.IsValid)
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Theaters = new SelectList(movieDropdownsData.Theaters, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(movie);
        }
        await _service.AddNewMovieAsync(movie);
        return RedirectToAction(nameof(Index));
    }

    //get - movies/edit

    public async Task<IActionResult> Edit(int id)
    {
        var movieDetails = await _service.GetMovieByIdAsync(id);
        if (movieDetails == null) return View("NotFound");

        var response = new NewMovieVM()
        {
            Id = movieDetails.Id,
            Name = movieDetails.Name,
            Description = movieDetails.Description,
            Price = movieDetails.Price,
            StartDate = movieDetails.StartDate,
            EndDate = movieDetails.EndDate,
            ImageURL = movieDetails.ImageURL,
            MovieCategory = movieDetails.MovieCategory,
            TheaterId = movieDetails.TheaterId,
            ProducerId = movieDetails.ProducerId,
            ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),
        };

        var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

        ViewBag.Theaters = new SelectList(movieDropdownsData.Theaters, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

        return View(response);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, NewMovieVM movie)
    {
        if (id != movie.Id) return View("NotFound");

        if (!ModelState.IsValid)
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Theaters = new SelectList(movieDropdownsData.Theaters, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(movie);
        }
        await _service.UpdateMovieAsync(movie);
        return RedirectToAction(nameof(Index));
    }

    //privacy and error views
    [AllowAnonymous]

    public IActionResult Privacy()
    {
        ViewData["Welcome"] = "Welcome To The Vault";
        ViewBag.Description = "This Is How We Do";
        return View();
    }

    [AllowAnonymous]

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FlixNTix/Controllers/OrderController.cs
using FlixNTix.Data.Cart;
using FlixNTix.Data.Interfaces;
using FlixNTix.Data.Repositories;
using FlixNTix.Data.Static;
using FlixNTix.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FlixNTix.Controllers;

[Authorize]
public class OrderController : Controller
{
    private readonly IMovieService _movieService;
    private readonly ShoppingCart _shoppingCart;
    private readonly IOrderService _orderService;
    public OrderController(IMovieService movieService, ShoppingCart shoppingCart, IOrderService orderService)
    {
        _movieService = movieService;
        _shoppingCart = shoppingCart;
        _orderService = orderService;
    }

    public async Task<IActionResult> Index()
    {
        string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        string userRole =User.FindFirstValue(ClaimTypes.Role);
        var orders = await _orderService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
        return View(orders);
    }
    public IActionResult ShoppingCart()
    {
        var items = _shoppingCart.GetShoppingCartItems();

        _shoppingCart.ShoppingCartItems = items;
        var response = new ShoppingCartVM()
        {
            ShoppingCart = _shoppingCart,
            ShoppingCartTotal = _shoppingCart.GetshoppingCartTotal()
        };

        return View(response);
    }

    public async Task<IActionResult> AddItemToShoppingCart(int id)
    {
        var item = await _movieService.GetMovieByIdAsync(id);
        if (item != null)
        {
            _shoppingCart.AddItemToCart(item);
        }
        return RedirectToAction(nameof(ShoppingCart));
    }

    public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
    {
        var item = await _movieService.GetMovieByIdAsync(id);

        if (item != null)
        {
            _shoppingCart.RemoveItemFromCart(item);
        }
        return RedirectToAction(nameof(ShoppingCart));
    }

    public async Task<IActionResult> CompleteOrder()
    {
        var items = _shoppingCart.GetShoppingCartItems();
        string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

        await _orderService.StoreOrderAsync(items, userId, userEmailAddress);
        await _shoppingCart.ClearShoppingCartAsync();

        return View("OrderCompleted");
    }
}

FlixNTix/Controllers/ProducerController.cs
using FlixNTix.Data;
using FlixNTix.Data.Interfaces;
using FlixNTix.Data.Static;
using FlixNTix.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlixNTix.Controllers;

[Authorize(Roles = UserRoles.Admin)]
public class ProducerController : Controller
{
    private readonly IProducerService _service;

    public ProducerController(IProducerService service)
    {
        _service = service;
    }

    //index
    [AllowAnonymous]

    public async Task<IActionResult> Index()
    {
        var allProducers = await _service.GetAllAsync();
        return View(allProducers);
    }

    //get - producer/details
    [AllowAnonymous]

    public async Task<IActionResult> Details(int id)
    {
        var producerDetails = await _service.GetByIdAsync(id);
        if (producerDetails == null) return View("NotFound");
        return View(producerDetails);
    }

    //get - producer/create

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("ProfilePictureURL,FullName,Bio")] Producer producer)
    {
        if (!ModelState.IsValid) return View(producer);

        _service.AddAsync(producer);
        return RedirectToAction(nameof(Index));
    }

    //get - producer/edit

    public async Task<IActionResult> Edit(int id)
    {
        var producerDetails = await _service.GetByIdAsync(id);
        if (producerDetails == null) return View("NotFound");
        return View(producerDetails);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePictureURL,FullName,Bio")] Producer producer)
    {
        if (!ModelState.IsValid) return View(producer);

        if (id == producer.Id)
        {
            _service.UpdateAsync(id, producer);
            return RedirectToAction(nameof(Index));
        }
        return View(producer);
    }

    //get - producer/delete

    public async Task<IActionResult> Delete(int id)
    {
        var producerDetails = await _service.GetByIdAsync(id);
        if (producerDetails == null) return View("NotFound");
        return View(producerDetails);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {

        var producerDetails = await _service.GetByIdAsync(id);
        if (producerDetails == null) return View("NotFound");

        await _service.DeleteAsync(id);
        return RedirectToAction(nameof(Index));

    }
}

FlixNTix/Controllers/TheaterController.cs
using FlixNTix.Data;
using FlixNTix.Data.Interfaces;
using FlixNTix.Data.Static;
using FlixNTix.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FlixNTix.Controllers;
[Authorize(Roles = UserRoles.Admin)]
public class TheaterController : Controller
{
    private readonly ITheaterService _service;

    public TheaterController(ITheaterService service)
    {
        _service = service;
    }

    //index 
    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        var allTheaters = await _service.GetAllAsync();
        return View(allTheaters);
    }

    //get - theater/create
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Theater theater)
    {
        if (!ModelState.IsValid) return View(theater);

        await _service.AddAsync(theater);
        return RedirectToAction(nameof(Index));
    }

    //get - theater/details
    [AllowAnonymous]

    public async Task<IActionResult> Details(int id)
    {
        var theaterDetails = await _service.GetByIdAsync(id);
        if (theaterDetails == null) return View("NotFound");
        return View(theaterDetails);
    }

    //get - theater/edit

    public async Task<IActionResult> Edit(int id)
    {
        var theaterDetails = await _service.GetByIdAsync(id);
        if (theaterDetails == null) return View("NotFound");
        return View(theaterDetails);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Theater theater)
    {
        if (!ModelState.IsValid) return View(theater);

        if (id == theater.Id)
        {
            _service.UpdateAsync(id, theater);
            return RedirectToAction(nameof(Index));
        }
        return View(theater);
    }

    //get - producer/delete

    public async Task<IActionResult> Delete(int id)
    {
        var theaterDetails = await _service.GetByIdAsync(id);
        if (theaterDetails == null) return View("NotFound");
        return View(theaterDetails);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {

        var theaterDetails = await _service.GetByIdAsync(id);
        if (theaterDetails == null) return View("NotFound");

        await _service.DeleteAsync(id);
        return RedirectToAction(nameof(Index));

    }
}

FlixNTix/Views/Movie/Create.cshtml
@using FlixNTix.Data.Enums
@model NewMovieVM

@{
    ViewData["Title"] = "Create a new movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4 class="text-white text-lg-center">Create A New Movie</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-warning"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group text-white">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control"/>
                                <span asp-validation-for="Name" class="text-warning"></span>
                            </div>
                            <div class="form-group text-white">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-warning"></span>
                            </div>
                            <div class="form-group text-white">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-warning"></span>
                            </div>
                            <div class="form-group text-white">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-warning"></span>
                            </div>
                            <div class="form-group text-white">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-warning"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group text-white">
                                <label asp-for="TheaterId" class="control-label"></label>
                                <select asp-for="TheaterId" class="form-control" asp-items="ViewBag.Theaters"></select>
                                <span asp-validation-for="TheaterId" class="text-warning"></span>
                            </div>
                            <div class="form-group text-white">
                                <label asp-for="MovieCategory" class="control-label"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-warning"></span>
                            </div>
                            <div class="form-group text-white">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-warning"></span>
                            </div>
                            <div class="form-group text-white">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                                <span asp-validation-for="ActorIds" class="text-warning"></span>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group text-white">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-warning"></span>
                            </div>
                            <div class="col-md-4 offset-4 text-center">
                                <img width="100%" id="ImageURLPreview" />
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-outline-info text-white float-end" style="margin-top: 5px" />
                                <a class="btn btn-outline-secondary text-white" style="margin-top: 5px" asp-action="Index">Home Page</a>
                            </div>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $("#ImageURL").on("change", function(){
            var output = document.getElementById("ImageURLPreview");
            output.src = $(this).val();
        })
    </script>
}

FlixNTix/Views/Movie/Details.cshtml
@*Always Define Model!!!*@
@model Movie

@*Define ViewData*@
@{
    ViewData["Title"] = "Movie Details";
}
    
@*Write Code - movie card layout for the movie page*@

<div class="row">
   <div class="col-md-8 offset-2">
            <div class="card mb-12">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-secondary">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @Model.Name
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <img src="@Model.ImageURL" width="100%" height="100%" alt="@Model.Name">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <p class="card-text">@Model.Description</p>
                            <p class="card-text"><b>Theater: </b>
                            <a asp-controller="Theater" asp-action="Details" asp-route-id="@Model.TheaterId">
                                @Model.Theater.Name
                            </a>
                            </p>
                            <p class="card-text"><b>Producer: </b>
                            <a asp-controller="Producer" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                            </p>
                            <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("MMM dd yy")</p>
                            <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("MMM dd yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE NOW</span>
                                }
                                else if (DateTime.Now > Model.EndDate)
                                {
                                    <span class="badge bg-danger text-white">NO LONGER AVAILABLE</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">COMING SOON</span>
                                }
                            </p>
                            <p class="card-text">
                                <b>Actors: </b>
                                <hr />
                                <div class="row">
                                    @foreach (var actor in Model.Actors_Movies)
                                    {
                                        <div class="col-sm-auto">
                                            <img class="border-info rounded-circle" src ="@actor.Actor.ProfilePictureURL" style="max-width: 125px" />
                                            <br />
                                            <a asp-controller="Actor" asp-action="Details" asp-route-id="@actor.ActorId">@actor.Actor.FullName</a>
                                        </div>
                                    }
                                </div>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer bg-secondary">
                            <p class="card-text">
                                <a class="btn btn-outline-light float-end" asp-action="Index">
                                    Back to List
                                </a>
                                <a class="btn btn-info text-white @((DateTime.Now > Model.EndDate) ? "disabled" : "")"
                               asp-controller="Order" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id">
                                    <i class="bi bi-cart-plus float-start"></i> Add to Cart (Price @Model.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>

FlixNTix/Views/Movie/Index.cshtml
@*Always Define Model!!!*@
@model IEnumerable<Movie>

@*Define ViewData*@
@{
    ViewData["Title"] = "List of Movies";
}
    
@*Write Code - movie card layout for the movie page*@

<div class="row">
   @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-secondary">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-end" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Theater: </b>@item.Theater.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("MMM dd yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("MMM dd yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE NOW</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">NO LONGER AVAILABLE</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">COMING SOON</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer bg-secondary">
                            <p class="card-text">
                                <a class="btn btn-outline-light float-end" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-info-circle" style="padding-right: 2px"sty></i> Show Details
                                </a>
                                <a class="btn btn-info text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")"
                               asp-controller="Order" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus float-start"></i> Add To Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Movie")